apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m3i8pasmp-java-springboot 
  janus-idp.io/tekton: m3i8pasmp-java-springboot
  backstage.io/kubernetes-id: m3i8pasmp-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m3i8pasmp-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml